// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blxutasramwycjohtmix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJseHV0YXNyYW13eWNqb2h0bWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDE0MTMsImV4cCI6MjA3NDExNzQxM30.tWg9aSOYhPBTVlmlWbc8uSeWDJHJItbzHdBv-QPe344";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});